In [2]:
import torch
torch.__version__

'2.0.1'

In [1]:
import numpy as np

In [2]:
numbers = np.linspace(5, 50, 24, dtype=int).reshape(4, -1)

In [3]:
numbers

array([[ 5,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26],
       [28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50]])

In [5]:
temperatures = np.array([29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
                         12.6, 49.9, 38.6, 31.3, 9.2, 22.2]).reshape(2, 2, 3)

In [6]:
temperatures.shape

(2, 2, 3)

In [8]:
temperatures

array([[[29.3, 42.1, 18.8],
        [16.1, 38. , 12.5]],

       [[12.6, 49.9, 38.6],
        [31.3,  9.2, 22.2]]])

In [9]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [11]:
print(a[0, 1])

2


In [12]:
print(a[1,2])

7


In [13]:
b[0, 0] = 77

In [14]:
print(a[0, 1])

77


In [15]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [16]:
row_r1 = a[1, :]
row_r1

array([5, 6, 7, 8])

In [17]:
row_r2 = a[1:2, :] # Rank 2 view of the second row of a
row_r2

array([[5, 6, 7, 8]])

In [18]:
# We can make the smae distinction when accessing columns of an array
col_r1 = a[:,  1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [20]:
# An example of integer arrany indexing.
# The returned array will be shape(3, =) and
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a[[0, 1, 2], [0, 1, 0]])

[1 4 5]


In [21]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
a[[0, 0], [1, 1]]

array([2, 2])

In [24]:
# Create a new arary from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
# Create an array of indices
b = np.array([0, 2, 0, 1])
b

array([0, 2, 0, 1])

In [27]:
# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

[ 1  6  7 11]


In [28]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 30
a

array([[31,  2,  3],
       [ 4,  5, 36],
       [37,  8,  9],
       [10, 41, 12]])

In [29]:
# Boolean array indexing: boolean array indexing lets you pick out arbitray of an array.
a = np.array([[1, 2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [30]:
# We use boolean array indexing to construct a rank 1 array 
# consisting of the elements of a corresponding to the True value
# of bool_idx
print(a[bool_idx])

[3 4 5 6]


In [31]:
# We can do all of the above in a single concise statement;
a[a > 2]

array([3, 4, 5, 6])

In [32]:
# Datatypes
x = np.array([1, 2, 3])
x.dtype

dtype('int64')

In [34]:
x = np.array([1.0, 2.0, 3.14])
x.dtype

dtype('float64')

In [35]:
# Force a particular datatype
x = np.array([1, 2], dtype=np.int64)

In [38]:
# Array math basic mathematical functions opearte elementwise on arrays on arrays,
# and are available both as operator overloads and as functions in the numpy module
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)
# Elemntwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [39]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [40]:
# Elementwise difference; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [41]:
# Elementwise division; both produce the array
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [42]:
# Elementwise square root; produces the array
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [43]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [44]:
v = np.array([9,10])
w = np.array([11, 12])


In [46]:
# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [48]:
# Numpy provides many useful functions most useful is sum
x = np.array([[1, 2], [3, 4]])
print(np.sum(x))
print(np.sum(x, axis=0)) # Compute sum of each column;
print(np.sum(x, axis=1)) # Compute sum of each rows

10
[4 6]
[3 7]


In [49]:
# The simplest example of this type of operation is transposing amatrix
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
