### Convolution Computer eyes

In [7]:
## Pytorch Convoluation
import torch
import torch.nn as nn

input_feat = torch.tensor([[4, 1, 7, 5], [4, 4, 2, 5], [7, 7, 2, 4], [1, 0, 2, 4]],
                         dtype=torch.float32).unsqueeze(0).unsqueeze(0)
print(input_feat)
print(input_feat.shape)

tensor([[[[4., 1., 7., 5.],
          [4., 4., 2., 5.],
          [7., 7., 2., 4.],
          [1., 0., 2., 4.]]]])
torch.Size([1, 1, 4, 4])


In [8]:
# Create 2 x 2 convolution
conv2d = nn.Conv2d(1, 1, (2, 2), stride=1, padding='same', bias=True)
# Random initilization paramters
print(conv2d.weight)
print(conv2d.bias)


Parameter containing:
tensor([[[[-0.3284,  0.2079],
          [-0.3301,  0.1613]]]], requires_grad=True)
Parameter containing:
tensor([-0.2808], requires_grad=True)


In [10]:
# Intervention on convolution kernel parameters
conv2d = nn.Conv2d(1, 1, (2, 2), stride=1, padding='same', bias=True)
# 卷积核要有四个维度（输入通道数，输出通道数，高，宽）
kernels = torch.tensor([[[[1,0], [2,1]]]], dtype=torch.float32)
conv2d.weight = nn.Parameter(kernels, requires_grad=False)
print(conv2d.weight)
print(conv2d.bias)


Parameter containing:
tensor([[[[1., 0.],
          [2., 1.]]]])
Parameter containing:
tensor([0.3621], requires_grad=True)


In [12]:
output = conv2d(input_feat)
print(output)

tensor([[[[16.3621, 11.3621, 16.3621, 15.3621],
          [25.3621, 20.3621, 10.3621, 13.3621],
          [ 9.3621,  9.3621, 10.3621, 12.3621],
          [ 1.3621,  0.3621,  2.3621,  4.3621]]]],
       grad_fn=<ConvolutionBackward0>)
